### PR TITLE
Exercise 1 Cleanup

### PR DESCRIPTION
**Pull request by Brett-Shelley**
Fixed an error in FastNovaMutation where it was never imploding. Remade LocalSearch to iterate correctly and return the iteration count instead of trip fitness. Removed arg input in made as I think it's not needed. Made (1+1) EA more efficient as well as renamed it.

### CODE REVIEW

**Review by MrInKryption — COMMENTED** [review]
Have seen.

**Review by a1705111 — COMMENTED** [review]
It would be best to be able to specify to run the code for exercise 1 or 2 (or eventually 3) based on a command line argument, rather than just commenting exercise 2 out.

**Comment by Protofall** [comment]
Seems good to me, but I agree with a1705111

**Review by Protofall — APPROVED** [review]
Seems good to me, but I agree with a1705111

**Review by pellway — APPROVED** [review]
seems good

**Pull request merged**
